### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'amp'  

### ISSUE THREAD

**Issue by suresh-s** [NVIDIA/nvidia-docker#1580]
Issue : AttributeError: module 'torch.cuda' has no attribute 'amp' 

Traceback (most recent call last):
  File "tools/train_net.py", line 15, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/miniconda3/lib/python3.7/site-packages/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/miniconda3/lib/python3.7/site-packages/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/miniconda3/lib/python3.7/site-packages/maskrcnn_benchmark/data/datasets/__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "/miniconda3/lib/python3.7/site-packages/maskrcnn_benchmark/data/datasets/coco.py", line 6, in <module>
    from maskrcnn_benchmark.structures.segmentation_mask import SegmentationMask
  File "/miniconda3/lib/python3.7/site-packages/maskrcnn_benchmark/structures/segmentation_mask.py", line 5, in <module>
    from maskrcnn_benchmark.layers.misc import interpolate
  File "/miniconda3/lib/python3.7/site-packages/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/miniconda3/lib/python3.7/site-packages/maskrcnn_benchmark/layers/nms.py", line 5, in <module>
    from apex import amp
  File "/miniconda3/lib/python3.7/site-packages/apex/__init__.py", line 23, in <module>
    from . import transformer
  File "/miniconda3/lib/python3.7/site-packages/apex/transformer/__init__.py", line 1, in <module>
    from apex.transformer import amp
  File "/miniconda3/lib/python3.7/site-packages/apex/transformer/amp/__init__.py", line 1, in <module>
    from apex.transformer.amp.grad_scaler import GradScaler
  File "/miniconda3/lib/python3.7/site-packages/apex/transformer/amp/grad_scaler.py", line 8, in <module>
    class GradScaler(torch.cuda.amp.GradScaler):
AttributeError: module 'torch.cuda' has no attribute 'amp'

Environment:
    Docker Base image : nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
    Pytorch 1.0.1
    torchvision 0.2.2
    apex 0.1

**Question:** 
 
Same application is working fine in Tesla T4 CUDA10.0 on the same software environment directly at  GPU server (without using docker image)

But if i use nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 with same software environment, I am getting error:  **AttributeError: module "torch.cuda" has no attribute amp**

What is the issue?  How can i solve it?
